// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using imm_check_server_example.Data;

#nullable disable

namespace immcheckserverexample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("imm_check_server_example.Models.ImmDocDS2019info", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("directBill")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("endProgram")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("official")
                        .HasColumnType("TEXT");

                    b.Property<string>("orgCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("postal")
                        .HasColumnType("TEXT");

                    b.Property<string>("sevisid")
                        .HasColumnType("TEXT");

                    b.Property<string>("sponsor")
                        .HasColumnType("TEXT");

                    b.Property<string>("startProgram")
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .HasColumnType("TEXT");

                    b.Property<string>("street1")
                        .HasColumnType("TEXT");

                    b.Property<string>("street2")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("ds2019info", (string)null);
                });

            modelBuilder.Entity("imm_check_server_example.Models.ImmDocI20", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("eduComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("eduLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("engNotRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("engRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("engRequirementsMet")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("institutionalKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("issDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("lengthOfStudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("minor")
                        .HasColumnType("TEXT");

                    b.Property<string>("prgEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("prgStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("primaryMajor")
                        .HasColumnType("TEXT");

                    b.Property<string>("secondMajor")
                        .HasColumnType("TEXT");

                    b.Property<string>("sevisid")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("I20Program", (string)null);
                });

            modelBuilder.Entity("imm_check_server_example.Models.ImmDocI94", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94exp")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94expds")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94iss")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94num")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94poe")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("I94", (string)null);
                });

            modelBuilder.Entity("imm_check_server_example.Models.ImmDocPassport", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpass")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("givenName")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("passexp")
                        .HasColumnType("TEXT");

                    b.Property<string>("passiss")
                        .HasColumnType("TEXT");

                    b.Property<string>("passnum")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("passport", (string)null);
                });

            modelBuilder.Entity("imm_check_server_example.Models.ImmDocVisaInfo", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("controlnumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampent")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampexp")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampiss")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampnum")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampplace")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("visastamp")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("visaInfo", (string)null);
                });

            modelBuilder.Entity("imm_check_server_example.Models.SponsoredStudentInformation", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("advisorEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("advisorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("advisorPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("financialDocsExpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("fundingSponsor")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("isFeeExempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("isSponsoredStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("isUSGovSponsored")
                        .HasColumnType("TEXT");

                    b.Property<string>("needsFinancialDocs")
                        .HasColumnType("TEXT");

                    b.Property<string>("sponsor")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("sponsoredStudentInformation", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
