// <auto-generated />
using System;
using ImmCheck.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImmCheck.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212190410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ImmCheck.Core.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ImmCheck.Core.Models.DS2019", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("directBill")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("endProgram")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("official")
                        .HasColumnType("TEXT");

                    b.Property<string>("orgCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("postal")
                        .HasColumnType("TEXT");

                    b.Property<string>("sevisid")
                        .HasColumnType("TEXT");

                    b.Property<string>("sponsor")
                        .HasColumnType("TEXT");

                    b.Property<string>("startProgram")
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .HasColumnType("TEXT");

                    b.Property<string>("street1")
                        .HasColumnType("TEXT");

                    b.Property<string>("street2")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("ds2019info");
                });

            modelBuilder.Entity("ImmCheck.Core.Models.FinancialSupport", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("academicTerm")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("dependentExp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("employmentFunds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("livingExpenses")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("otherExpAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("otherExpDesc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("otherFundsAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("otherFundsDesc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("personalFunds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("remarks")
                        .HasColumnType("TEXT");

                    b.Property<int?>("schoolFundsAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("schoolFundsDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("sevisid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("tuition")
                        .HasColumnType("INTEGER");

                    b.HasKey("recnum");

                    b.ToTable("sevisI20Financial");
                });

            modelBuilder.Entity("ImmCheck.Core.Models.I20", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("eduComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("eduLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("engNotRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("engRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("engRequirementsMet")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("institutionalKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("issDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("lengthOfStudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("minor")
                        .HasColumnType("TEXT");

                    b.Property<string>("prgEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("prgStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("primaryMajor")
                        .HasColumnType("TEXT");

                    b.Property<string>("secondMajor")
                        .HasColumnType("TEXT");

                    b.Property<string>("sevisid")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("I20Program");
                });

            modelBuilder.Entity("ImmCheck.Core.Models.I94", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94exp")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94expds")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94iss")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94num")
                        .HasColumnType("TEXT");

                    b.Property<string>("i94poe")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("I94");
                });

            modelBuilder.Entity("ImmCheck.Core.Models.Institution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Did")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("ImmCheck.Core.Models.Passport", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpass")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("givenName")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("passexp")
                        .HasColumnType("TEXT");

                    b.Property<string>("passiss")
                        .HasColumnType("TEXT");

                    b.Property<string>("passnum")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("passport");
                });

            modelBuilder.Entity("ImmCheck.Core.Models.SponsoredStudentInfo", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("advisorEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("advisorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("advisorPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("financialDocsExpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("fundingSponsor")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("isFeeExempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("isSponsoredStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("isUSGovSponsored")
                        .HasColumnType("TEXT");

                    b.Property<string>("needsFinancialDocs")
                        .HasColumnType("TEXT");

                    b.Property<string>("sponsor")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("sponsoredStudentInformation");
                });

            modelBuilder.Entity("ImmCheck.Core.Models.VisaInfo", b =>
                {
                    b.Property<long>("recnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("controlnumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("datestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("idnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipfsCID")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampent")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampexp")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampiss")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampnum")
                        .HasColumnType("TEXT");

                    b.Property<string>("stampplace")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("visastamp")
                        .HasColumnType("TEXT");

                    b.HasKey("recnum");

                    b.ToTable("visaInfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ImmCheck.Core.Models.ApplicationUser", b =>
                {
                    b.HasOne("ImmCheck.Core.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ImmCheck.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ImmCheck.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImmCheck.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ImmCheck.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
